name: 'coverage'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        submodules: recursive

    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: '3.13'

    - name: Run coverage
      run: |
        ./.github/run.sh tox -e coverage
        ./.github/run.sh coverage html --directory=htmlcov

    - name: Report coverage
      run: ./.github/run.sh coverage report -m --skip-covered

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: VUnit_coverage
        path: htmlcov
