name: 'coverage'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run coverage
      run: |
        ./.github/run.sh tox -e coverage
        ./.github/run.sh coverage html --directory=htmlcov

    - name: Report coverage
      run: ./.github/run.sh coverage report -m --skip-covered

    - uses: actions/upload-artifact@v3
      with:
        name: VUnit_coverage
        path: htmlcov
