name: 'docs'

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # https://github.com/tox-dev/tox/issues/1468
  PY_COLORS: 1

jobs:

  docs:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        pip install -U pip --progress-bar off
        pip install -U virtualenv tox --progress-bar off

    - name: Build docs
      run: tox -e py313-docs -- --color

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
      with:
        name: VUnit-site
        path: .tox/py313-docs/tmp/docsbuild/

    - name: '🚀 Publish site'
      if: github.event_name != 'pull_request' && github.ref_name == 'master'
      run: >-
        GH_DEPKEY='${{ secrets.VUNIT_GITHUB_IO_DEPLOY_KEY }}'
        ./.github/publish_site.sh
        '${{ github.repository }}'
